services:
  http:
    image: ghcr.io/taoky/presenced:master
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3001"
    env_file:
      - .env
    volumes:
      # timezone file
      - /etc/localtime:/etc/localtime:ro
